apiVersion: v2
name: librephotos
description: Helmchart used to install Librephotos in a microservice manner
version: 0.202215.3
appVersion: 2022w15
home: https://github.com/varet80/publiccharts/tree/main/charts/librephotos
kubeVersion: '>=1.21.0-0'
keywords:
- photolibrary
- photos
- librephotos
maintainers:
- name: Vassilis Aretakis
  e-mail: v.aretakis@gmail.com
  url: https://github.com/varet80
sources:
 - https://github.com/LibrePhotos/librephotos
 - https://hub.docker.com/r/reallibrephotos
dependencies:
- name: postgresql
  version: "=> 11.0.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
- name: redis
  version: "=> 16.0.0"
  repository: "https://charts.bitnami.com/bitnami"
  condition: redis.enabled
